spring:
  batch.job.enabled: false # 어플리케이션 시동 시, Job 시작 해제
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MYSQL;
    schema: classpath:/org/springframework/batch/core/schema-h2.sql

logging.level.com.deeplify.tutorial.batch: debug